[tool.poetry]
name = "scout-discord-bot-modal"
version = "0.1.0"
description = ""
authors = ["aplchiangh <alex.boquis@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scoutos = "^0.1.20"
discord-py = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
